@startuml

state Signin {
    [*] --> SigninIdle
    SigninIdle --> SigninIdle : UC-5.3.Failed
    SigninIdle --> [*] : UC-5.2.Success / UC-5.1.Signed in
    SigninIdle --> [*] : UC-5.4.Canceled
    
}



@enduml