@startuml

state Signin {
    [*] --> SigninIdle
    SigninIdle --> SigninIdle : UC_5.3.Failed
    SigninIdle --> [*] : UC_5.2.Success / UC_5.1.Signed in
    SigninIdle --> [*] : UC_5.4.Canceled

}


@enduml