@startuml

[*] --> SM_1.EnterWord
[*] --> SM_5.Signup : \
    UC_5.5.2.Reseive Email with signup url \n\
    UC_5.5.3.Go to signedup url

SM_1.EnterWord --> SM_2.Interupt : UC_1.Enter word
SM_1.EnterWord -up-> SM_4.Signin : UC_5.Signing in

SM_2.Interupt --> SM_3.Dashboard : \
    UC_1.1.Interpret a word as a keyword \n\
    / \n\
    UC_3.Show a list of similar words \n\
    UC_3.1.Show the similarity between words

SM_2.Interupt --> SM_3.Dashboard : \
    UC_1.2.Interpret a word as a title \n\
    not signed in \n\
    / \n\
    UC_3.Show a list of similar words \n\
    UC_3.1.Show the similarity between words

SM_2.Interupt --> SM_3.Dashboard : \
    UC_1.2.Interpret a word as a title \n\
    signed in \n\
    / \n\
    UC_3.Show a list of similar words \n\
    UC_3.1.Show the similarity between words \n\
    UC_4.Show related titles \n\
    UC_4.1.Show the similarity between word and title



SM_3.Dashboard --> SM_2.Interupt : UC_1.Enter word

SM_4.Signin --> SM_1.EnterWord : UC_5.1.Success
SM_4.Signin --> SM_4.Signin : UC_5.2.Failed

SM_5.Signup --> SM_1.EnterWord : UC_5.5.4.2.Password is valid


@enduml