@startuml

(UC-5.Signing in) .. (UC-5.1.Signed in)
(UC-5.Signing in) .. (UC-5.2.Success) : extend
(UC-5.Signing in) .. (UC-5.3.Failed) : extend
(UC-5.Signing in) .. (UC-5.4.Canceled) : extend

@enduml
