@startuml

(UC-5.Signing in) .. (UC-5.1.Signed in)
(UC-5.Signing in) .. (UC-5.2.Success) : extend
(UC-5.Signing in) .. (UC-5.3.Failed) : extend
(UC-5.Signing in) .. (UC-5.4.Canceled) : extend

(UC-5.Signing in) .. (UC-5.5.Signing up) : extend
(UC-5.5.Signing up) .. (UC-5.5.1.Set Email address) : include
(UC-5.5.Signing up) .. (UC-5.5.2.Reseive Email with signup url) : include
(UC-5.5.Signing up) .. (UC-5.5.3.Go to signedup url) : include
(UC-5.5.Signing up) .. (UC-5.5.4.Set password twice) : include

(UC-5.5.1.Set Email address) .. (UC-5.5.1.1.The Email addres is already registered) : extend
(UC-5.5.1.Set Email address) .. (UC-5.5.1.2.The Email addres is not registered yet) : extend

(UC-5.5.4.Set password twice) .. (UC-5.5.4.1.Password is invalid) : extend
(UC-5.5.4.Set password twice) .. (UC-5.5.4.2.Password is valid) : extend

@enduml
